name: CI with PostgreSQL
on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  phpunit:
    name: PHP ${{ matrix.php }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [ 80, 81 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: make build

      - name: PHP Codeception tests for PHP ${{ matrix.php }}
        run: make test${{ matrix.php }}