name: Run tests
on:
  pull_request:
    branches: [ master ]
    paths-ignore:
      - 'README.md'
  push:
    branches: [ master ]
    paths-ignore:
      - 'README.md'

jobs:
  codeception:
    name: PHP ${{ matrix.php }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [ '8.1' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: PHP Codeception tests for PHP ${{ matrix.php }}
        run: |
          make build v=${{ matrix.php }}
          make test v=${{ matrix.php }}
